language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
matrix:
  fast_finish: true
  allow_failures:
    - rvm:
      - 2.3.0
      - 2.2.4
services:
  - mysql
before_script:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS janky_test;"
  - bundle exec rake db:migrate --trace
script: "bundle exec script/test"
